version: "3.3"

services:
  wds-mysql:
    container_name: wds-mysql
    image: mysql:5.7.22
    volumes:
      - wds_mysql_db:/var/lib/mysql
    ports:
      - "14000:3306"
    env_file:
      - wds-mysql.env
    networks:
      - wds_internal_net
  wds-app:
    container_name: wds-app
    environment:
      - SPRING_PROFILES_ACTIVE=production
    image: lvovlink/wds-docker:0.0.3
    depends_on:
      - "wds-mysql"
    ports:
      - "8080:8080"
    networks:
      - wds_internal_net


volumes:
  wds_mysql_db:

networks:
  wds_internal_net: